apiVersion: v1
kind: Pod
metadata:
    name: client-Pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: nuenook/multi-client
          ports:
            - containerPort: 3000